# Generated by Django 3.1.14 on 2022-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20220414_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default=2, upload_to='pokemon_images', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
